name: Test

on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::debug::a"
          echo "::notice::b"
          echo "::warning::c"
          echo "::error::d"
          echo "::debug::a\nb"
