name: Test

on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::error file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
